name: 'Publish'

permissions:
  contents: write
  id-token: write

env:
  CI: true

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Create pull request
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: release ${{ github.event.release.tag_name }}'
          branch: ${{ github.event.repository.default_branch }}
          file_pattern: package.json
